### ISSUE TITLE
Add mechanism to enable template-matching based normalization techniques 

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/GaNDLF#302]
**Is your feature request related to a problem? Please describe.**
Currently, GaNDLF can handle simple normalization techniques (z-score or image-net normalization), and it is not enough for some specialized tasks or datasets, such as histology.

**Describe the solution you'd like**
Add the option to integrate template-matching based normalization techniques, such as the following:
- [x] histogram matching
- [x] histogram equalization
- [x] adaptive histogram equalization
- [ ] vahadane
- [ ] macenko
- [ ] reinhard

**Describe alternatives you've considered**
N.A.

**Additional context**
- Histogram matching is [available in SimpleITK](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1HistogramMatchingImageFilter.html)
- For the histology normalization techniques, implementations that don't use `spams` should be considered (since it is no longer actively maintained); 
  - There are 2 such implementations: from [tiatoolbox](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/tiatoolbox/tools/stainnorm.py) and [histocartography](https://github.com/histocartography/histocartography/blob/3ab203af4c7a6a0d7b7ca2c35a0c672ef0f00655/histocartography/preprocessing/stain_normalizers.py)
  - I am leaning more towards the latter because the dependencies are defined in a better way, and it can be grafted more easily into GaNDLF's preprocessing module
- In `data_preprocessing`, assign a key `histogram_matching` that would be defined in the following manner:
```yaml
data_preprocessing:
{
  histogram_matching:
  {
    method: simple, # simple: histogram matching from SimpleITK; vahadane/macenko/reinhard from their respective implementations
    target: path_to_image_to_be_used_for_template, # this is the image from where the histogram target will be taken
  }
}
```
